# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.2-node-browsers
        environment:
          PG_HOST: localhost
          PG_USER: ubuntu
          RAILS_ENV: test
          RACK_ENV: test
          AWS_S3_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
          AWS_S3_BUCKET: example_s3_bucket
          AWS_S3_REGION: us-west-2
          AWS_S3_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYzEXAMPLEKEY
          BASE_ECPM: 400
          BUFFER_ENABLED: false
          DEFAULT_HOST: codefund.app
          ENABLED_FEATURES: jobs
          HUBSPOT_ENABLED: false
          PG_TIMEOUT_IN_SECONDS: 3
          RAILS_MAX_THREADS: 10
          REDIS_CACHE_URL: redis://127.0.0.1:6379
          REDIS_QUEUE_URL: redis://127.0.0.1:6379
          SCOUT_SAMPLE_RATE: 0.3
          DATABASE_URL: "postgres://ubuntu@localhost:5432/code_fund_ads_test"

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:11.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: code_fund_ads_test
      - image: circleci/redis:5.0.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: sudo apt install -y postgresql-client || true

      - run:
          name: update bundler
          command: |
            gem install bundler:2.0.1

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Set up DB
          command: bundle exec rails db:drop db:create db:structure:load --trace

      - run:
          name: run tests
          command: bundle exec rails test

      - run:
          name: run system tests
          command: bundle exec rails test:system
